### ISSUE TITLE
Autosizing not updating in Simulator

### ISSUE THREAD

**Issue by retsohuang** [SwiftUI-Plus/TextView#2]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*

Yes

## General Information

 - Project version:
1.1.0
 
 - Platform/OS version: 
iOS 13.2
 
 - IDE version:
Version 12.5.1
 
 - Devices: 
iPhone 11
 
 - Any related GitHub issues:
Nope

## Describe the bug
TextView's size didn't update 

## Steps to reproduce
*Provide numbered steps to follow that reproduce the bug.*
1. Download [Demo](https://github.com/SwiftUI-Plus/Demo)
2. Delete `Presentation` and `Browsers` packages since they can't run on Xcode 12.5.1
3. Delete `PresentationDemo` and `ScrollViewDemo` since the package has been deleted
4. Run the project on the simulator and choose TextView

## Expected behavior
The `text2` string should be fully displayed

<img src="https://user-images.githubusercontent.com/785920/135728350-4568aeda-9ab5-46fd-ae28-d7a325ec47b1.png" width="500" />

## Stack trace, compiler error, code snippets
Nope

## Screenshots
Only display the first line of string

<img src="https://user-images.githubusercontent.com/785920/135728359-58c0e870-8cc3-428a-bd2b-770996c8f287.png" width=500 />

## Additional context
Changing `TextView.swift`'s `calculatedHeight` default value to `0` fix the problem.

**Comment by shaps80** [comment]
Can you confirm this works on device (vs Simulator)?

**Comment by shaps80** [comment]
I'm confused as to what issue you're having here. From the screenshots all looks ok?

**Comment by retsohuang** [comment]
> I'm confused as to what issue you're having here. From the screenshots all looks ok?

The screenshot of `Expected behavior` is captured after I modify `TextView.swift`'s `calculatedHeight` to `0`

**Comment by shaps80** [comment]
@retsohuang I'm thinking you're misunderstanding how its supposed to work, maybe?

So the 1st screenshot is correct. The view is automatically sizing itself to fit the text, growing and shrinking as required.

The 2nd screenshot it what you'd expect from a TextField (which SwiftUI already provides) where only a single line of text is possible, no wrapping.

Setting the `calculatedHeight = 0` will actually break autosizing completely, so that's definitely not a 'solution' to any problem.

Let me know if that clarifies things, but I think you're looking for a `lineLimit` feature on this view, which is not currently supported as `TextField` already performs that task perfectly.
