### ISSUE TITLE
Inherit font from environment

### ISSUE THREAD

**Issue by lhunath** [SwiftUI-Plus/TextView#8]
## Describe the feature
Currently, the font can be configured using a custom `func font(_ font: UIFont) -> TextView`.
SwiftUI however is built around properties exposed to the hierarchy through the environment.
It would be great if `TextView` could adopt this and read the font from `EnvironmentValues.font`.
Similarly it could adopt the other standardized properties exposed through the environment.

## Is your feature request related to a problem? 
`TextView` does not respect the `.font` set in the view hierarchy and needs to be manually configured.

## Proposed solution
Remove `font(_:UIFont)` and read the font from the environment using `@Environment`. Regrettably there does not appear to be an easy way to convert a `SwiftUI.Font` into a `UIKit.UIFont`.

**Comment by shaps80** [comment]
Hey thanks for this. I've actually recently done this for other relevant values (lineSpacing, etc.) – I just haven't shipped it yet ;)

While its possible to inject the font via the environment, as you've mentioned it'd need to be a UIFont, meaning I'd need to create a different `EnvironemntKey`, but totally possible to implement something like: `@Environment(\.uiFont)`.

I've also now improved several other areas so that modifiers can be added anywhere in the hierarchy now as well, rather than just on the `TextView` itself (which was an annoyance in terms of ordering in particular.

I will get this out shortly.

Re: Font > UIFont, that's why I wrote the API-matching (mostly) UIFont helpers to at least make it feel consistent.

**Comment by shaps80** [comment]
Upon further reflection I've explored this idea and would make font behave differently (at least in some case) to all other properties. For most other values, it makes very little sense to support a custom EnvironmentKey for a pre-existing definition.

I'm not happy with the inconsistency this would introduce so I will not be included this change sorry.

For a little extra reference, I considered another common use-case `foregroundColor`. You can likely already imagine the implications of trying to introduce something similar.

- I cannot read the `foregroundColor` from the environment since its internal (I hope  change this)
- Therefore I'd have to consider a new key, with what name? Naming here would be tricky IMO
- This would account for color and font, the 2 most commonly required customisations, but others are equally important when we're discussing a TextView (vs TextField).

So, sorry but I don't feel this change is feasible.

**Comment by lhunath** [comment]
That makes sense. I wonder whether a workable alternative solution might be to set the `TextView`'s default font to one that is auto-detected from the `EnvironmentValue.font`, if it can be, and fall back to `.body` if it can't be.
For instance, it should be relatively simple to do tests for the standard text styles:
```
let defaultFont: UIFont
@Environment(\.font) var font: Font
if font == .title {
    defaultFont = .preferredFont(forTextStyle: .title)
} ... else {
    defaultFont = .preferredFont(forTextStyle: .body)
}
```

**Comment by shaps80** [comment]
Interesting idea, I haven’t checked if its equatable but there’s a little more to it than that tbh. For example you can ‘modify’ font with `weight` and `design` and I _think_ its a closed type (non-public). I’ll investigate and check but I’m not sure this is possible. Cool idea though.

**Comment by shaps80** [comment]
Right just checked quickly and as I thought, you can’t discover the internal modifications of the font. So your idea _might_ work for absolute default styles, or you could potentially try and reproduce all variants and test each of those as well to get closer to the intended/expected font.

But again

- This would only solve for `font`, since we can’t insect the environment for `foregroundColor` (an equally worthy value)
- I feel this is out-of-scope for this library to make this kind of change

Sorry ;)
